spring:
  datasource:
    url: jdbc:postgresql://localhost:5001/prime
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

server:
  port: 8085
